steps:
 # 1단계 => docker-compose -f docker-compose.prod.yaml build
 #  cloudbuild.yaml가 있는 경로를 명시해줘야된다
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/section18/18-04-deploy-with-kubernetes-ci-cd/backend/docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/section18/18-04-deploy-with-kubernetes-ci-cd/backend/docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/qkjk-backend-nestjs qkjk-backend-sha256-1=asia.gcr.io/backend-462005/qkjk-backend:0.7
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/qkjk-backend-nestjs
      - qkjk-backend-sha256-1=asia.gcr.io/backend-462005/qkjk-backend:0.9
      # 여기 버전이 docker-compose.prod.yaml이랑 같은지 확인해야됨
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1


# serviceAccount써주고, options도 써줘야됨
serviceAccount: projects/backend-462005/serviceAccounts/ci-builder@backend-462005.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY