version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # 소스코드 동기화를 위해 src폴더를 공유해준다
      # 이때 맨 앞에 점을 꼭 찍어준다아아아아악!
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker # 도커용 env는 이렇게 적용해준다

  my-database:
    # platform: linux/86_64 # 이건 성능을 올려주기 위해 있는것
    image: mysql
    environment:
      MYSQL_DATABASE: 'mydocker' # 이렇게 써주면 도커 안에서 데이터베이스가 실행되면서 자동으로 mydocker라는 데이터베이스가 하나 생긴다(로컬에서는 myproject로 만들었는데 도커에서는 mydocker로 써주자)
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    # mysql의 포트는 3306
