# 로컬 컴퓨터와 도커 컴퓨터를 volumes로 연결해서 docker-compose build를 매번 할 필요 없이, 각각의 index.js를 수정하면 바로바로 반영되도록 하자

version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # 내 컴퓨터의 index.js와 도커 컴퓨터 안의 myfolder안에 있는 index.js를 연결해준다
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      # 만약 파일 하나하나 하기 귀찮으면 src 폴더를 하나 만들어서 거기에 파일을 다 넣은 다음에 그 폴더 전체를 공유해도 된다
      # - ./src:myfolder/src
    ports:
      - 4000:4000
  my-database:
    image: mongo:5
    ports:
      - 27017:27017

    # volume연결 후에 처음에 한번만 docker-compose build를 해주고, up을 해주면, 그 다음부터는 수정하면 자동으로 내 컴퓨터와 도커 컴퓨터 모두에서 코드 업데이트가 된다(노드몬이 코드 수정을 감지해서 서버 리스타팅이 된다)
